version: '3'

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=impero
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=impero
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Rome
      - MYSQL_CNX_STRING=impero:password@tcp(mysql)/impero?parseTime=true&loc=Local
    command: /root/impero -pass=password -debug=true
    restart: on-failure
    depends_on:
      - mysql
